[package]
name = "conv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.11"
tokio = { version = "1", features = ["rt-multi-thread"] }
eframe = "0.22"
egui = "0.22"
font-kit = "0.11"
whisper_cli = "0.1"