[package]
name = "conv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.13.0"
eframe = "0.26"
egui = "0.26"
font-kit = "0.12.0"
clap_builder = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
reqwest = "0.11"
anyhow = "1"
whisper-rs = "0.8"
uuid = { version = "1", features = ["v4"] }
audrey = { version = "0.3", features = ["wav"] }
once_cell = "1"
image = "0.24"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"